# Work on a trusty VM
sudo: required
dist: trusty

# Allow only arpl-website branch (not arpl-website.dev) and branches containing a */ci-travis/* part
branches:
  only:
    - arpl-website
    - /.*\/ci-travis\/.*/

script :
- cd $TRAVIS_BUILD_DIR
# Do nothing
- echo -e "Directory pushed on $(date)" > ci-travis_info.txt

after_success:
# Deploy website
- "curl --ftp-create-dirs -T * -u $FTP_USER:$FTP_PASSWORD ftp://$FTP_URL/www/test/"